# Generated by Django 4.2.7 on 2025-07-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecoclub", "0003_passwordresetrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwordresetrequest",
            name="new_password",
        ),
        migrations.AddField(
            model_name="passwordresetrequest",
            name="desired_password",
            field=models.CharField(
                blank=True,
                help_text="User's desired new password",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="passwordresetrequest",
            name="reason",
            field=models.TextField(
                blank=True, help_text="User's reason for password reset", null=True
            ),
        ),
    ]
